name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  fvp: ^0.19.0
  confetti: ^0.7.0
  audioplayers: ^6.1.0
  flutter_webrtc: ^0.11.7
  video_player: ^2.8.7
  fl_chart: ^0.69.0
  grpc: ^4.0.1
  path: ^1.9.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  protobuf: ^3.1.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 900

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/songs/
    - assets/fonts/
    - assets/characters/
    - assets/sound-effects/
